import { useEffect, useState } from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { useCreateHomePopupLead, useHomePopupCampaigns, type PopupCampaign } from "@/hooks/useHomePopupCampaign";

const preview: PopupCampaign = { id: "preview", is_active: true, image_url: "https://pglbbwycichoaeltulin.supabase.co/storage/v1/object/public/class-images/1785399912274.png", badge: "FA POTTERY STUDIO", title: "Cerámica para hacer con tus manos", body: "Recibí novedades, próximos workshops y propuestas para crear en FA Pottery.", cta_label: "Quiero recibir novedades", objective: "lead", cta_url: null, discount_code: null, success_title: "¡Gracias!", success_body: "Te avisaré pronto.", show_name: true, fields: [], interests: ["Workshops y clases regulares", "Piezas y novedades"], privacy_text: "Podés retirar tu consentimiento cuando quieras.", starts_at: null, ends_at: null };

export default function EventPromoModal() {
  const { data } = useHomePopupCampaigns(true); const campaign = data?.[0] || (import.meta.env.DEV ? preview : undefined); const createLead = useCreateHomePopupLead();
  const [open, setOpen] = useState(false); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [extra, setExtra] = useState<Record<string, string>>({}); const [interests, setInterests] = useState<string[]>([]); const [done, setDone] = useState(false);
  useEffect(() => { if (!campaign) return; if (!import.meta.env.DEV && sessionStorage.getItem(`popup-${campaign.id}`)) return; const timer = setTimeout(() => { setOpen(true); if (!import.meta.env.DEV) sessionStorage.setItem(`popup-${campaign.id}`, "1"); }, 800); return () => clearTimeout(timer); }, [campaign]);
  if (!campaign) return null;
  const form = campaign.objective === "lead" || campaign.objective === "discount";
  const action = async (event: React.FormEvent) => { event.preventDefault(); if (campaign.objective === "info") return setOpen(false); if (campaign.objective === "link") { window.location.assign(campaign.cta_url || "/"); return; } await createLead.mutateAsync({ campaign_id: campaign.id, email: email.toLowerCase(), full_name: name || null, interests, form_data: extra, marketing_consent: true }); setDone(true); };
  return <DialogPrimitive.Root open={open} onOpenChange={setOpen}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-[100] bg-foreground/70 backdrop-blur-sm" /><DialogPrimitive.Content aria-describedby={undefined} className="fixed left-1/2 top-1/2 z-[100] w-[calc(100%-2rem)] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto border border-foreground bg-background shadow-xl focus:outline-none md:grid md:max-h-[90vh] md:grid-cols-2">{campaign.image_url && <img src={campaign.image_url} alt="" className="h-48 w-full object-cover md:h-full" />}<div className="relative p-6 md:p-9"><DialogPrimitive.Close aria-label="Cerrar" className="absolute right-4 top-4"><X className="h-5 w-5" /></DialogPrimitive.Close>{done ? <><DialogPrimitive.Title className="font-serif text-3xl">{campaign.success_title}</DialogPrimitive.Title><p className="mt-3 body-text">{campaign.success_body}</p>{campaign.objective === "discount" && campaign.discount_code && <p className="mt-5 border border-foreground p-3 text-center font-medium">{campaign.discount_code}</p>}</> : <form onSubmit={action} className="space-y-4">{campaign.badge && <p className="label-sm">{campaign.badge}</p>}<DialogPrimitive.Title className="font-serif text-4xl leading-none">{campaign.title}</DialogPrimitive.Title>{campaign.body && <p className="body-text">{campaign.body}</p>}{form && <>{campaign.show_name && <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Tu nombre (opcional)" />}{campaign.fields.map((field) => <Input key={field.id} required={field.required} value={extra[field.id] || ""} onChange={(e) => setExtra((current) => ({ ...current, [field.id]: e.target.value }))} placeholder={field.label} type={field.type} />)}<Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Tu email" />{campaign.interests.map((interest) => <label key={interest} className="flex gap-2 text-sm"><Checkbox checked={interests.includes(interest)} onCheckedChange={(checked) => setInterests((current) => checked ? [...current, interest] : current.filter((item) => item !== interest))} />{interest}</label>)}<p className="text-xs text-muted-foreground">{campaign.privacy_text || "Podés retirar tu consentimiento cuando quieras."}</p></>}<Button className="w-full" type="submit" disabled={createLead.isPending}>{campaign.cta_label}</Button>{createLead.isError && <p className="text-sm text-destructive">No pudimos guardar tu email. Probá nuevamente.</p>}</form>}</div></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;
}
